-- Isolated test fixture, not a production migration or a full Supabase dump.
CREATE TABLE public.atleta (
 id_atleta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL, apelido text, nome_alternativo text, posicao text, grupo text, data_nascimento date
);
CREATE TABLE public.grupo_medida (id_grupo_medida integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome text NOT NULL);
CREATE TABLE public.medida (id_medida integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome text NOT NULL, id_grupo_medida integer REFERENCES grupo_medida);
CREATE TABLE public.partida (id_partida integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, equipe text, adversario text, data timestamp);
CREATE TABLE public.medida_valor (
 id_medida_valor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_atleta integer REFERENCES atleta, id_partida integer REFERENCES partida,
 id_medida integer REFERENCES medida, valor double precision, valor_texto text, data timestamp NOT NULL
);
INSERT INTO grupo_medida (nome) VALUES ('Saltos'), ('termografia'), ('GPS');
INSERT INTO medida (nome, id_grupo_medida)
SELECT name, 1 FROM unnest(ARRAY['CMJ1','CMJ2','CMJ3','MAIOR_CMJ','SJ1','SJ2','SJ3','MAIOR_SJ']) name;
INSERT INTO medida (nome, id_grupo_medida)
SELECT name, 2 FROM unnest(ARRAY['MASSA','EVA_DOR','PERNA_DIREITA_FRENTE','PERNA_ESQUERDA_FRENTE','PERNA_DIREITA_VERSO','PERNA_ESQUERDA_VERSO','SOMA_FRENTE','SOMA_VERSO','OBSERVACOES']) name;
CREATE VIEW public.vw_medidas_saltos AS
SELECT a.id_atleta, a.nome atleta, a.posicao, a.grupo, mv.data::date data_coleta,
 MAX(mv.valor) FILTER (WHERE m.nome='CMJ1') cmj1,
 MAX(mv.valor) FILTER (WHERE m.nome='CMJ2') cmj2,
 MAX(mv.valor) FILTER (WHERE m.nome='CMJ3') cmj3,
 MAX(mv.valor) FILTER (WHERE m.nome='MAIOR_CMJ') maior_cmj,
 MAX(mv.valor) FILTER (WHERE m.nome='SJ1') sj1,
 MAX(mv.valor) FILTER (WHERE m.nome='SJ2') sj2,
 MAX(mv.valor) FILTER (WHERE m.nome='SJ3') sj3,
 MAX(mv.valor) FILTER (WHERE m.nome='MAIOR_SJ') maior_sj
FROM atleta a JOIN medida_valor mv USING (id_atleta) JOIN medida m USING (id_medida)
WHERE m.id_grupo_medida=1 GROUP BY a.id_atleta, mv.data::date;
CREATE VIEW public.vw_medida_termografia AS
SELECT a.id_atleta, a.nome jogador, mv.data data_coleta,
 MAX(mv.valor) FILTER (WHERE m.nome='MASSA') massa,
 MAX(mv.valor) FILTER (WHERE m.nome='EVA_DOR') eva_dor,
 MAX(mv.valor) FILTER (WHERE m.nome='SOMA_FRENTE') frente,
 MAX(mv.valor) FILTER (WHERE m.nome='SOMA_VERSO') verso,
 MAX(mv.valor_texto) FILTER (WHERE m.nome='OBSERVACOES') observacoes
FROM atleta a JOIN medida_valor mv USING (id_atleta) JOIN medida m USING (id_medida)
WHERE m.id_grupo_medida=2 GROUP BY a.id_atleta, mv.data;
CREATE VIEW public.vw_medidas_gps AS
SELECT a.nome atleta, a.posicao, a.grupo, mv.data::date data_coleta, p.equipe, p.adversario,
 MAX(mv.valor) FILTER (WHERE m.nome='Distance (km)') distance_km,
 MAX(mv.valor) FILTER (WHERE m.nome='Accel&Decel Efforts') accel_de_cel_efforts,
 MAX(mv.valor) FILTER (WHERE m.nome='Accel&Decel Efforts Per Minute') accel_de_cel_efforts_per_minute,
 MAX(mv.valor) FILTER (WHERE m.nome IN ('High Speed Distance','High Speed Distance (km)')) high_speed_distance,
 MAX(mv.valor) FILTER (WHERE m.nome='High Speed Efforts') high_speed_efforts,
 MAX(mv.valor) FILTER (WHERE m.nome='Max Acceleration') max_acceleration,
 MAX(mv.valor) FILTER (WHERE m.nome='Max Deceleration') max_deceleration,
 MAX(mv.valor) FILTER (WHERE m.nome='Maximum Velocity (km/h)') maximum_velocity_km_h,
 MAX(mv.valor) FILTER (WHERE m.nome='Meterage Per Minute') meterage_per_minute,
 MAX(mv.valor) FILTER (WHERE m.nome='Player Load Per Minute') player_load_per_minute,
 MAX(mv.valor) FILTER (WHERE m.nome='Sprint Efforts') sprint_efforts
FROM atleta a JOIN medida_valor mv USING (id_atleta) JOIN medida m USING (id_medida)
LEFT JOIN partida p USING (id_partida)
WHERE m.id_grupo_medida=3 GROUP BY a.id_atleta, mv.data::date, p.id_partida;
